### ISSUE TITLE
Python 3.8

### ISSUE THREAD

**Issue by xyproto** [pfalcon/python-compiler.old#9]
Hi,

FYI, `python-compiler` is now an [Arch Linux package](https://www.archlinux.org/packages/community/any/python-compiler/).

The plan is to use it in connection with making Shedskin run with Python 3.

Hopefully, the differences between Python 3.5 and 3.8 are minimal enough that `python-compiler` should also work with 3.8. It looks good so far.

Please let me know if you make a new release tag and wish the package was updated as well, by clicking the ["Flag Package Out-of-Date"](https://www.archlinux.org/packages/community/any/python-compiler/flag/) link.

Best regards,
Alexander F. Rødseth

**Comment by pfalcon** [comment]
Per the title, this ticket is duplicate of https://github.com/pfalcon/python-compiler/issues/7 . I recommend to review that ticket to be in loop re: current plans of supporting next CPython versions (which are none).

I'll respond to package maintenance matters later a time permits, though again, #7 should give some ideas what suggestions would be.

**Comment by pfalcon** [comment]
Ah, please don't forget to read README too, that would explain why this package is useless for Shedskin ;-).

**Comment by xyproto** [comment]
Since #7 now also covers Python 3.8, I'll just close this one.

Not quite sure what to do to upgrade Shedskin in relation to Arch Linux. If Shedskin is just unmaintained and only supporting Python 2, I guess it will be eventually moved from the official repository to the AUR.

`python-compiler` looks like it can be useful for several different projects, so I'll keep it around even if it's not used by Shedskin. :slightly_smiling_face:

**Comment by pfalcon** [comment]
> Hopefully, the differences between Python 3.5 and 3.8 are minimal

As #7 mentions, differences between CPython 3.5 and 3.6 are big enough - it switched from **byte**code to **word**code. Well, in grand order of things, those aren't that big, but enough of a chore. I personally and humbly consider CPython to be deadend in Python's evolution, so not fancy doing an exercise just for it. As #7 mentions, I started to write a bytecode compiler from scratch, but it doesn't target CPython's VM, but instead [Pycopy](https://github.com/pfalcon/pycopy)'s VM.

That's also where my interest re: Shedskin lies - I'd like to port it to Pycopy. And as Pycopy is implementation of Python3, I'd like to help with porting Shedskin to Python3.

> The plan is to use it in connection with making Shedskin run with Python 3.

As the README here says:

> The porting project concentrates on the conversion of AST (as provided by the builtin "ast" module) to bytecode and code objects. The original Python2 package included another important part: conversion of concrete parse tree into Abstract Syntax Tree (AST).

In other words, there's nothing of interest here for Shedskin porting to Python3, instead, the whole interest lies in https://github.com/shedskin/shedskin/pull/261, as I already pointed in https://github.com/shedskin/shedskin/issues/264 .

> FYI, python-compiler is now an Arch Linux package.

My recommendation would be, until too late, to remove that package. This project is effectively a "research" project, it's not really useful for "end users" due to its tight connection to a specific CPython version (3.5), which is now even relatively dated version. So, only outcome of the distro package can be confusion for users and maintenance/support burden for the maintainer. Please save yourself from that, and spend your time on something more useful ;-). For example, if you're eager to package up something, please consider my cute https://github.com/pfalcon/pycopy ;-).

> If Shedskin is just unmaintained and only supporting Python 2, I guess it will be eventually moved from the official repository to the AUR.

That's what will happen if interested people won't get together and upgrade it, yeah. I mentioned where my interest in Shedskin lies, but given that Pycopy requires a lot of much more mundane work, stuff like Shedskin is on (long) backburner. And actually, I'm interested in Python in general, of which Shedskin is outstanding, but only one specimen. Given that Pycopy's focus is on minimalism, it's so happens that I'm more interested in minimalist compilers. For example, this holiday season, I finally ported https://github.com/sdiehl/numpile to Pycopy. Wait time was ~6 months.

(Please don't package numpile as Arch package, again, it's a "research" project.)

Hopefully, this info is useful.
